- templates/app-template-react-typescript/package.json
- templates/app-template-react-typescript/src/App.tsx
- templates/app-template-react-typescript/src/index.tsx
This was necessary for me to see the app load on the page. A blank screen would be shown otherwise, with an error in the console:
```
TypeError: Z is undefinedreact-dom.js:340:200
React 3
reactDom_production_min
reactDom_production_min
reactDom_production_min
createCommonjsModule http://localhost:3000/web_modules/common/_commonjsHelpers-f5462f22.js:4
<anonymous> React
InnerModuleEvaluation self-hosted:1604
InnerModuleEvaluation self-hosted:1593
evaluation self-hosted:1558
```
The removal of the extension in `index.tsx`  was necessary for `lintall:tsc` not to complain.
I believe a similar fix should be done in the React template.
> fix(react-ts): move react deps to webDependencies

- templates/app-template-preact/README.md
Hello!
This PR fixes a small typo on the `app-template-preact/README.md` file.  It basically replaces "React" with "Preact" 😛
> Replace React with Preact on app-template-preact/README

- packages/plugin-svelte/plugin.js
This provides the `filename` argument to `svelte.preprocess`, which some preprocessors require.
> Provide filename argument to svelte.preprocess.

- packages/plugin-babel/plugin.js
Disabling ast-generation increases speed of the total transformation time.
> make @snowpack/plugin-babel compatible with v2

- packages/plugin-bundle-webpack/package.json
- packages/plugin-bundle-webpack/plugin.js
I added the extendConfig plugin option. Here, both these versions should do the same thing:
snowpack.config.json:
```
{
extends: '@snowpack/app-scripts-react',
devOptions: { bundle: true },
plugins: [
[
'@snowpack/plugin-bundle-webpack',
{
extendConfig: {
devtool: 'source-map',
mode: 'development'
}
},
],
],
scripts: { 'bundle:*': '@snowpack/plugin-bundle-webpack' },
}
```
AND
snowpack.config.js:
```
module.exports = {
extends: '@snowpack/app-scripts-react',
devOptions: { bundle: true },
plugins: [
[
'@snowpack/plugin-bundle-webpack',
{
extendConfig: (config) => ({
...config,
devtool: 'source-map',
mode: 'development',
}),
},
],
],
scripts: { 'bundle:*': '@snowpack/plugin-bundle-webpack' },
};
```
> Added extendConfig plugin option to plugin-bundle-webpack

- templates/app-template-lit-element-typescript/types/import.d.ts
- templates/app-template-react-typescript/src/index.tsx
- templates/app-template-react-typescript/types/import.d.ts
- templates/app-template-react/src/index.jsx
- templates/app-template-svelte/src/index.js
- templates/app-template-vue/src/index.js
/cc @JoviDeCroock @rixo
This adds basic HMR support to the templates mentioned in the title. In all 3 templates, we place an `import.meta.hot.accept()` call at the application root that will catch all updates, reload any updated files, dispose the old app (if needed) and then finally remount the app without triggering a full page load.
This builds on our work in https://github.com/pikapkg/esm-hmr, and requires `snowpack@2.0.0-rc.3` or higher to run properly.
> add HMR support to react, svelte, and vue templates

- LICENSE
- packages/app-scripts-preact/snowpack.config.js
- packages/app-scripts-react/babel.config.json
- packages/app-scripts-react/snowpack.config.js
- packages/plugin-babel/plugin.js
- packages/plugin-react-refresh/package.json
- packages/plugin-react-refresh/plugin.js
- templates/app-template-react-typescript/babel.config.json
- templates/app-template-react/babel.config.json
- templates/app-template-react/src/App.jsx
- yarn.lock
This PR adds fast refresh support for `@snowpack/plugin-react`. 
Note: that this is **currently blocked from merging** due to the fact that it needs react-dom to be installed with NODE_ENV = 'development'. Today, we do all installations with NODE_ENV = 'production'. Unless you first run `snowpack install --env NODE_ENV=development`, fast refresh  won't work.
Enabling this NODE_ENV support for dev vs. prod was on my roadmap, but this may have just pushed it up.
> Add react fast refresh support

- packages/app-scripts-preact/babel.config.json
This PR fixes TypeScript support for projects using the Preact template
According to the [docs](https://babeljs.io/docs/en/babel-preset-typescript) for `@babel/preset-typescript`
> - `jsxPragma` - defaults to `React`  
>   Replace the function used when compiling JSX expressions. This is so that we know that the import is not a type import, and should not be removed.
Changing this to `h` solves the issue.
This doesn't solve the issue for Parcel bundler though, as adding `@snowpack/plugin-parcel` to the project's config will remove all the plugins from the config that it's extending from, this is a separate issue however.
> fix typescript support for preact template

- packages/plugin-parcel/plugin.js
Right now the parcel plugin only supports bundling of a single entrypoint.
> Support bundling on all HTML entrypoints for the parcel plugin

- packages/plugin-webpack/package.json
- packages/plugin-webpack/plugin.js
- yarn.lock
- Always minify JS and CSS (todo: HTML?)
- Lock down babel to only compile via preset-env, by default
- clean up matchers
/cc @lajoiemedia  not sure if you'll agree with the new restrictions, but they come from a place of trying to codify "The Snowpack Way" to separate your concerns between build and bundle. 
Mainly, that all files have already been "built" by the time they get to the bundler, so that the bundlers only responsibility is to optimize for production as well as possible. In that vein, minifying should always be enabled (why would you ever want to optimize only a little?) and babel-loader should be hardcoded to only transpile for production (custom user-provided babel config would have already been run earlier in the build).
TODO: Add …
> Small webpack plugin improvements

- packages/plugin-webpack/plugin.js
The build with `@snowpack/plugin-webpack` will fail if there are no files other than index.html in the public directory.
Repository for reproduction:
https://github.com/yuheiy/create-snowpack-app-plugin-webpack-only-index.html
Set the `noErrorOnMissing` option to `copy-webpack-plugin` to fix the problem.
> Do not give an error when only index.html exists

- packages/app-scripts-lit-element/tsconfig.base.json
- packages/app-scripts-preact/tsconfig.base.json
- packages/app-scripts-react/tsconfig.base.json
This PR adds [`resolveJsonModule`](https://www.staging-typescript.org/tsconfig#resolveJsonModule) to tsconfig on every template:
- `packages/app-scripts-lit-element/tsconfig.base.json` - used by `templates/app-template-lit-element-typescript/tsconfig.json`
- `packages/app-scripts-preact/tsconfig.base.json`
- `packages/app-scripts-react/tsconfig.base.json` - used by `templates/app-template-react-typescript/tsconfig.json`
There's no `app-template-preact-typescript` that will use `tsconfig.base.json` in `app-scripts-preact` yet.
Resolve https://github.com/pikapkg/create-snowpack-app/issues/90
> Add resolveJsonModule to template's tsconfigs

- templates/app-template-react-typescript/src/App.tsx
`React.Props` is deprecated and generally not used.
The most common approach is either to specify the exact props you want (`{ children: React.ReactNode }` or use the `React.FC<Props>` to type the entire function.
> Remove deprecated type usage

- templates/app-template-11ty/package.json
- templates/app-template-blank/package.json
- templates/app-template-lit-element-typescript/package.json
- templates/app-template-lit-element/package.json
- templates/app-template-preact/package.json
- templates/app-template-react-typescript/package.json
- templates/app-template-react/package.json
`'` causes issues on Windows. The solution is to use `\"` instead
> Update templates to use windows friendly scripts

- packages/create-snowpack-app/index.js
To address #96
```
- Using template vue
- Creating a new project in /Volumes/.../new-dir
[ERROR] Template is not properly marked as a CSA template (Missing "csa-template" keyword in package.json).
[ERROR] Cannot continue safely. Exiting...
```
```
- Using template vue
- Creating a new project in /Volumes/.../new-dir
[ERROR] The template is not a CSA template (missing "csa-template" keyword in package.json), check the template name to make sure you are using the current template name.
[ERROR] Cannot continue safely. Exiting...
```
> Rephrase error message for template which is not properly marked as a CSA template

- packages/plugin-vue/plugin.js
Support all template preprocessors that are supported by [`@vue/compiler-sfc`](https://www.npmjs.com/package/@vue/compiler-sfc) (uses https://github.com/tj/consolidate.js/ under the hood, see consolidate.js README for full list of languages).
Example using `pug`:
```vue
<template lang="pug">
.App
a(href="//vuejs.org") Hi
</template>
```
```js
// package.json
"devDependencies": {
// ...
"pug": "^3.0.0"
}
```
> add vue template preprocessor lang support

- templates/app-template-lit-element-typescript/types/import.d.ts
- templates/app-template-react-typescript/types/import.d.ts
Looks like we forgot to add the `env` key to the `importMeta` type definition.
Brought up in https://github.com/pikapkg/snowpack/pull/394#issuecomment-639154557
> Update import meta typing to include env

- README.md
Usage:
```
npx create-snowpack-app new-dir --template app-template-reason-react [--use-yarn]
```
- Built on top of [@snowpack/app-template-react](https://github.com/pikapkg/create-snowpack-app/blob/master/templates/app-template-react)
- Added supports for [ReasonML](https://reasonml.github.io/) using [BuckleScript](https://bucklescript.github.io) to compile `*.re` to `*.bs.js`
- Added [reason-react](https://reasonml.github.io/reason-react/) package
- Re-wrote original JS in ReasnoML
> Add app-template-reason-react link to README

- .github/workflows/test.yml
- .gitignore
- package.json
- packages/create-snowpack-app/index.js
- test/runner.test.js
- yarn.lock
This adds a test that tests all templates in this directory.
It takes the local bin in `./packages/create-snowpack-app` as the CLI command, and it installs the local templates in `./templates/*`. This means when it runs on every PR, it’s testing the actual changes to this codebase, and not testing against changes published against npm.
⚠️ The only bad part is that these templates themselves rely on external packages to run. So we’re kind of hoping that all those install & build before Jest times out.
> Add automated test for all templates

- packages/plugin-parcel/plugin.js
- packages/plugin-webpack/plugin.js
Add support for `baseUrl` in the new Snowpack 2.5
> update bundlers to Snowpack 2.5

- packages/app-scripts-preact/jest/babelTransform.js
- packages/app-scripts-preact/tsconfig.base.json
Adding `h` as the pragma to the base tsconfigfile allows typescript to find and use Preact's JSX type definitons instead of the nonexistent React bindings.
Adding it to Jest's babel configuration prevents it from mistakenly stripping the import of `h` as unused when reading a TSX file during testing.
> Support `h` as the JSX pragma consistently throughout `app-scripts-preact`
